---
kind: Service
apiVersion: v1
metadata:
  name: kitchensink
  labels:
    app: eap72-basic-s2i
    app.kubernetes.io/component: eap72-basic-s2i
    app.kubernetes.io/instance: eap72-basic-s2i
    application: kitchensink
    template: eap72-basic-s2i
    xpaas: 1.2.0
  annotations:
    description: The web server's http port.  
spec:
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: kitchensink
---
kind: Service
apiVersion: v1
metadata:
  name: kitchensink-ping
  labels:
    app: eap72-basic-s2i
    app.kubernetes.io/component: eap72-basic-s2i
    app.kubernetes.io/instance: eap72-basic-s2i
    application: kitchensink
    template: eap72-basic-s2i
    xpaas: 1.2.0
  annotations:
    description: The JGroups ping port for clustering.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ipFamilies:
    - IPv4
  ports:
    - name: ping
      protocol: TCP
      port: 8888
      targetPort: 8888
  internalTrafficPolicy: Cluster
  clusterIPs:
    - None
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: kitchensink


