kind: Secret
apiVersion: v1
metadata:
  name: kitchensink-database-secret
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: kitchensink-app
stringData:
  DB_HOST: kitchensink-db
  DB_USERNAME: luke
  DB_PASSWORD: secret
  DB_NAME: kitchensink
type: Opaque
