#!/bin/sh

. ./image-env.sh

podman tag ${PROJECT_ID}:${JVM_VERSION} $REGISTRY/$REGISTRY_USER_ID/${PROJECT_ID}:${JVM_VERSION}
podman tag ${PROJECT_ID}:${JVM_VERSION} $REGISTRY/$REGISTRY_USER_ID/${PROJECT_ID}:latest

podman push $REGISTRY/$REGISTRY_USER_ID/${PROJECT_ID}:${JVM_VERSION}
podman push $REGISTRY/$REGISTRY_USER_ID/${PROJECT_ID}:latest
