- op: replace
  path: /spec/replicas
  value: 1
- op: add
  path: /spec/template/metadata/labels
  value:
    application: kitchensink
    deploymentConfig: kitchensink
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: kitchensink-app