apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-puller
  namespace: {{ .Values.cicdNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: kitchensink-sa
  namespace: demo-7-dev
- kind: ServiceAccount
  name: kitchensink-sa
  namespace: demo-7-test