---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jenkinsServiceAccountName }}
  namespace: {{ .Values.cicdNamespace }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.jenkinsServiceAccountName }}-edit-rolebinding
  namespace: {{ .Values.cicdNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.jenkinsServiceAccountName }}
    namespace: {{ .Values.cicdNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{ if .Values.username }}
  name: {{ .Values.jenkinsServiceAccountName }}-sync-clusterrole-{{ .Values.username }}
  {{ else }}
  name: {{ .Values.jenkinsServiceAccountName }}-sync-clusterrole
  {{ end }}
  namespace: {{ .Values.cicdNamespace }}
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - "*"
  - apiGroups:
      - image.openshift.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - build.openshift.io
    resources:
      - "*"
    verbs:
      - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  {{ if .Values.username }}
  name: {{ .Values.jenkinsServiceAccountName }}-sync-clusterrolebinding-{{ .Values.username }}
  {{ else }}
  name: {{ .Values.jenkinsServiceAccountName }}-sync-clusterrolebinding
  {{ end }}
  namespace: {{ .Values.cicdNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.jenkinsServiceAccountName }}
    namespace: {{ .Values.cicdNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  {{ if .Values.username }}
  name: {{ .Values.jenkinsServiceAccountName }}-sync-clusterrole-{{ .Values.username }}
  {{ else }}
  name: {{ .Values.jenkinsServiceAccountName }}-sync-clusterrole
  {{ end }}


