apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: "{{ .Values.appName }}-{{ .Values.arcoSaerServiceName }}-bc"
  namespace: {{ .Values.cicdNamespace }}
  labels:
    app: "{{ .Values.appName }}-{{ .Values.arcoSaerServiceName }}-app"
spec:
  source:
    type: Git
    git:
      uri: '{{ .Values.gitUrl }}/{{ .Values.gitUsername }}/arco-saer-cde-mig'
      ref: develop
    # contextDir: '.'
    sourceSecret:
      name: {{ .Values.gitPatSecretName }}
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Containerfile.7.2
      buildArgs:
        - name: JBOSS_EAP_BUILDER_IMAGE
          value: "registry.redhat.io/jboss-eap-7/eap72-openshift:1.2"
      env:
        - name: MAVEN_MIRROR_URL
        - name: MAVEN_ARGS_APPEND
          value: '-Dcom.redhat.xpaas.repo.jbossorg'
        - name: ARTIFACT_DIR
        - name: MAVEN_ARGS
        - name: GIT_SSL_NO_VERIFY
          value: 'true'
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.appName }}-{{ .Values.arcoSaerServiceName }}:latest"
  