kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: jboss-eap-openshift
  namespace: {{ .Values.cicdNamespace }}
  annotations:
    openshift.io/display-name: Red Hat JBoss EAP 7.2
    openshift.io/image.dockerRepositoryCheck: '2022-08-24T12:04:10Z'
    openshift.io/provider-display-name: 'Red Hat, Inc.'
    version: '1.2'
spec:
  lookupPolicy:
    local: false
  tags:
    - name: '1.0'
      annotations:
        supports: 'eap:7.2,javaee:7,java:8'
        sampleContextDir: kitchensink
        openshift.io/display-name: Red Hat JBoss EAP 7.2
        sampleRef: openshift
        version: '1.0'
        tags: 'builder,eap,javaee,java,jboss,hidden'
        sampleRepo: 'https://github.com/jbossas/eap-quickstarts/openshift'
        description: Red Hat JBoss EAP 7.2 S2I Image
        iconClass: icon-eap
      from:
        kind: DockerImage
        name: 'registry.redhat.io/jboss-eap-7/eap72-openshift:1.0'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Local
    - name: '1.1'
      annotations:
        supports: 'eap:7.2,javaee:7,java:8'
        sampleContextDir: kitchensink
        openshift.io/display-name: Red Hat JBoss EAP 7.2
        sampleRef: openshift
        version: '1.1'
        tags: 'builder,eap,javaee,java,jboss,hidden'
        sampleRepo: 'https://github.com/jbossas/eap-quickstarts/openshift'
        description: Red Hat JBoss EAP 7.2 S2I Image
        iconClass: icon-eap
      from:
        kind: DockerImage
        name: 'registry.redhat.io/jboss-eap-7/eap72-openshift:1.1'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Local
    - name: '1.2'
      annotations:
        supports: 'eap:7.2,javaee:7,java:8'
        sampleContextDir: kitchensink
        openshift.io/display-name: Red Hat JBoss EAP 7.2
        sampleRef: openshift
        version: '1.2'
        tags: 'builder,eap,javaee,java,jboss,hidden'
        sampleRepo: 'https://github.com/jbossas/eap-quickstarts/openshift'
        description: Red Hat JBoss EAP 7.2 S2I Image
        iconClass: icon-eap
      from:
        kind: DockerImage
        name: 'registry.redhat.io/jboss-eap-7/eap72-openshift:1.2'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Local
    - name: latest
      annotations:
        supports: 'eap:7.2,javaee:7,java:8'
        sampleContextDir: kitchensink
        openshift.io/display-name: Red Hat JBoss EAP 7.2
        sampleRef: openshift
        version: latest
        tags: 'builder,eap,javaee,java,jboss,hidden'
        sampleRepo: 'https://github.com/jbossas/eap-quickstarts/openshift'
        description: Red Hat JBoss EAP 7.2 S2I Image
        iconClass: icon-eap
      from:
        kind: DockerImage
        name: 'registry.redhat.io/jboss-eap-7/eap72-openshift:latest'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Local
