kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: "{{ .Values.appName }}-{{ .Values.kitchensinkServiceName }}"
  namespace: {{ .Values.cicdNamespace }}
  labels:
    app: eap72-basic-s2i
    app.kubernetes.io/component: eap72-basic-s2i
    app.kubernetes.io/instance: eap72-basic-s2i
    application: kitchensink-app
    template: eap72-basic-s2i
    xpaas: 1.2.0
spec:
  lookupPolicy:
    local: false