---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "{{ .Values.kitchensinkServiceName }}-bc"
  namespace: "{{ .Values.cicdNamespace }}"
  labels:
    app: "{{ .Values.kitchensinkServiceName }}-app"
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.kitchensinkServiceName }}:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: '{{ .Values.kitchensinkBuilderImage }}'
      env:
        - name: MAVEN_MIRROR_URL
        - name: MAVEN_ARGS_APPEND
          value: '-Dcom.redhat.xpaas.repo.jbossorg'
        - name: ARTIFACT_DIR
      incremental: true
      forcePull: true
  postCommit: {}
  source:
    type: Git
    git:
      uri: '{{ .Values.kitchensinkRepoUrl }}'
      ref: '{{ .Values.kitchensinkRevision }}'
  triggers:
    - type: GitHub
      github:
        secret: PauCH5th
    - type: Generic
      generic:
        secret: DXNNoNSt
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
