apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  annotations:
    tekton.dev/displayName: Image Digest cluster task
    tekton.dev/pipelines.minVersion: '0.19'
    tekton.dev/tags: 'jq, oc'
  name: image-digest

  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: redhat
spec:
  description: >-
    These Task finds an image and returns the digest.
  params:
    - description: Image Tag Name
      name: IMAGE_TAG_NAME
      type: string
    - description: Image Tag Namespace
      name: IMAGE_TAG_NAMESPACE
      type: string
    - default: quay.io/atarazana/jq:0.0.2
      description: the image used where the yq binary is
      name: TASK_IMAGE
      type: string
  results:
    - description: Digest of the image just built.
      name: IMAGE_DIGEST
    - description: Digest of the image just built without "sha256:"
      name: IMAGE_DIGEST_CLEAN
  steps:
    - image: $(params.TASK_IMAGE)
      name: eval
      resources: {}
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh

        IMAGE_DIGEST = oc get imagetags $(params.IMAGE_TAG_NAME) -n $(params.IMAGE_TAG_NAMESPACE) | jq -r .image.metadata.name
        echo "IMAGE_DIGEST: ${IMAGE_DIGEST}"
        NEW_IMAGE_TAG = ("${IMAGE_DIGEST}" =~ /.*\:(.*)/)[0][1]
        echo "NEW_IMAGE_TAG: ${NEW_IMAGE_TAG}"

        echo -n ${IMAGE_DIGEST} > $(results.IMAGE_DIGEST)
        echo -n ${NEW_IMAGE_TAG} > $(results.IMAGE_DIGEST_CLEAN)
  workspaces:
    - mountPath: /workspace/source
      name: source
