apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/managed-by: argocd

resources:
- ./base/kitchensink-bc.yaml
- ./base/kitchensink-db-deployment.yaml
- ./base/kitchensink-db-svc.yaml
- ./base/kitchensink-dc.yaml
- ./base/kitchensink-is.yaml
- ./base/kitchensink-route.yaml
- ./base/kitchensink-svc.yaml