kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: kitchensink
  labels:
    app: eap72-basic-s2i
    app.kubernetes.io/component: eap72-basic-s2i
    app.kubernetes.io/instance: eap72-basic-s2i
    application: kitchensink
    template: eap72-basic-s2i
    xpaas: 1.2.0
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'kitchensink:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'jboss-eap72-openshift:1.2'
      env:
        - name: MAVEN_MIRROR_URL
        - name: MAVEN_ARGS_APPEND
          value: '-Dcom.redhat.xpaas.repo.jbossorg'
        - name: ARTIFACT_DIR
      incremental: true
      forcePull: true
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/atarazana/kitchensink'
      ref: main
  triggers:
    - type: GitHub
      github:
        secret: PauCH5th
    - type: Generic
      generic:
        secret: DXNNoNSt
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial

