---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.arcoSaerServiceName }}-source-pvc"
  namespace: {{ .Values.cicdNamespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sourceWorkspaceSize }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.arcoSaerServiceName }}-cache-pvc"
  namespace: {{ .Values.cicdNamespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cacheWorkspaceSize }}